version: '3.8'

services:
  blog:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm hexo server -p 4000

  # 生产环境服务
  blog-prod:
    build: .
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
    command: pnpm hexo server -p 4000
    profiles:
      - production
